name: CI
on: 
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install eslint -g && npm install
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx